### ISSUE TITLE
All tabs show "no data" in both logged-in & logged-out states

### ISSUE THREAD

**Issue by duncancarroll** [status-im/commiteth#57]
[comment]: # (Please replace ... with your information. Remove < and >)

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

#### Expected behavior
[comment]: # Expect to see a feed of Activity, repos, etc.

#### Actual behavior
[comment]: # No feeds are shown.  The site appears broken.

### Reproduction
[comment]: # Visit https://commiteth.com/ 

### Additional Information

[comment]: # (Browser and version)
* Browser: Tried Safari and Chrome (Mac OS Sierra) No JS errors seen.

[comment]: # (OS version)
* Operating System: Mac OS Sierra

**Comment by tpatja-broadsoft** [comment]
Thanks for the report. We moved commiteth.com to the mainnet a couple of days ago and use a new database, because it does not make sense to show existing bounties that use the testnet. Once people start using CommitETH with real ether, the activity feed, top hunters and open bounties views will again show data.

**Comment by onbjerg** [comment]
@tpatja-broadsoft Since this is true, the issue should be closed, right?

**Comment by tpatja** [comment]
True, closing.
