### ISSUE TITLE
UX: Seems like stuck on "Deploying contract..."

### ISSUE THREAD

**Issue by benmorrow** [status-im/commiteth#66]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user, I want to understand the current status of CommitETH for peace of mind.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: For the hackathon project GitHub Issues, it seems like CommitETH is stuck on "Deploying contract...". Here's a screenshot: 
![screen shot 2017-06-09 at 12 25 18 pm](https://user-images.githubusercontent.com/5604/26991455-3781e184-4d0f-11e7-8a55-8833c7baac93.png)

#### Expected behavior
Maybe it could say something like, "Waiting for pull request..."

**Comment by tpatja** [comment]
There was only one bounty in the system with a "stuck" contract deployment from several days ago. It was created before we took the new contract to use and while the bot account balance had run out. Contract deployments no longer get stuck, they just take longer (3-30 minutes instead of <2 minutes).

The text should be changed to "Deploying contract.. usually takes 3-30 minutes". Saying the system is waiting for a PR would be incorrect.

Another issue (actual bug) is that CommitETH UI keeps showing the old title for a bounty issue after it gets changed on Github. I will create another issue for that and close this one.
