### ISSUE TITLE
Commiteth.com still display closed issues

### ISSUE THREAD

**Issue by 3esmit** [status-im/commiteth#73]
Many issues are closed in GitHub and commiteth still show them as open.

**Comment by tpatja** [comment]
This is because cancelling/closing logic has not been implemented. Currently the only way to close a bounty is via a merged PR.

An easy way to fix this would be just to not show bounties for closed github issues. But a more proper way would be to return the bounty's possible funds when an issue is closed manually without merging a PR.

**Comment by 3esmit** [comment]
This is one more case for using other contract or enhancing wallet to accept refund from deposits.

**Comment by tpatja** [comment]
Returning funds and supporting manual issue close is now tracked in #73
