### ISSUE TITLE
https://commiteth.com does not work((

### ISSUE THREAD

**Issue by AnthonyAkentiev** [status-im/commiteth#98]
### User Story

As a user, I want to be able to work with https://commiteth.com site so that it will add bounty comments for open issues.

#### Expected behavior
The bounty contract should be deployed to the 'issue'

#### Actual behavior
The 'bounty' contract is never deployed

### Reproduction
1) go to https://commiteth.com
2) log in 
3) go to 'Repositories'
4) Click on 'Add' button. Enable access to one of repos
5) Add new issue to the repo
6) Label it with 'bug' and 'bounty' labels
7) Wait 15-20 minutes

Result:
1) New issue comment is added by commiteth with a 'Deploying contract (usually takes 1-2 minutes)' status.

**Comment by tpatja** [comment]
This was caused by our low gas price of 1 gwei. To save costs we lowered it to 1 gwei from 4 gwei last June and deployments slowed down but still worked. Now 1 gwei deployment transactions no longer seem to get mined.

Gas price is now set to 6 gwei and bounty contract deployments should work again.

**Comment by AnthonyAkentiev** [comment]
@tpatja Thx!
